### ISSUE TITLE
Unnessessary hue shift

### ISSUE THREAD

**Issue by jsniezek** [razorltd/sasscolourfunctioncalculator#4]
In the attached screenshot, both the source and target colors have a hue of 160, so the adjust-hue step shouldn't be necessary in this case. I put (what I believe is) the correct command below the output in the screenshot. 

<img width="690" alt="color adjust oddness" src="https://cloud.githubusercontent.com/assets/1707469/18475106/46cd6d0c-7993-11e6-9a29-6940785ba14b.png">

**Comment by aij** [comment]
Actually, I'm seeing unnecessary saturation adjustments too.

Eg: `lighten(#334d64, 50)` == `#baccdc`, but this tool says `lighten(saturate(adjust-hue(#334d64, 0.0720), 0.2420), 50.0000)`

**Comment by laurienicholas** [comment]
I've pushed an update that does away with this error. Feel free to reopen/raise again if you spot it on any other examples.
